language: r
dist: trusty
sudo: true
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
env:
  global:
  - secure: OV4B2udhdnyVUKrEMzCLs49j2Hce/2lvukvw9Nr+p4Vj1q0oPF5dyAwXFpjyZT70gtgykgq/x43nXSv2BFK5jnWSssdS1eXZ+UPa2o3ApUpi1gR27h5c0erIdiqIETLBf1gzH0nhmZ9bbY5qfOLJU/Wj7M/bYymhzzLvvGy4ipqahFm37tgduMxlKbwRWk5Uh58Ql+nv/Poj3TTvDIAPfP0HQrO4bmcggmtN+Fdy0lDhUwfl5wrxcFcgpy2HFjM58DaYqGkmQ9NeowRzmbQdm5tNVy2eCHpHb6IiwaIgCrDfF8gAyf9bpCGIPSnqmWPW/3NAqN3qvhkrW1Y1suJ39NmONNhzKHC0E/lAsseauTC14KntlCW7D+WQy3v4KgG8pkUXyxIn5qxSfI/ThA1rkXQwATVOuGm9enmzayvae6q8r7Uo5d+SoaC3vjI/cyTi+fchAG3JGI1mTxeovKtIMO4Vx0nquMBkUAOvqCO/ao4un+mX4jLFwFu5tvkY/SELitKiaTZL+VjCIYbJUmRwJALc0h1iLXQrJC87u5V6hRKSORLo23CEZpWw9RSYTmsu26VXIDkmfLYdmUwOwY1YtNsvGy6UA2J2MIzIoSVkf6aMEjj3EvTVWi92kAkVxNPu16Pw1rCcRbl+lhpkPzr6yP621uTWDDnNkPHJAiaEsvc=
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev
before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh
script:
  - ./_build.sh
  - ./_deploy.sh
r_binary_packages:
  - sp
  - rgeos
r_github_packages:
  - dkahle/ggmap
  - pbiecek/archivist
  - cran/survival
  - cran/bindrcpp
  - cran/shiny
  - cran/htmlwidgets
  - cran/udunits2
